##**Verification of Numerical Patterns in Surah An-Nahl** **bold text**

This notebook is created to computationally verify the numerical and linguistic patterns highlighted in the article:

https://numericalmiraclesofquran.com/surah-an-nahl

## **Objective**

The goal of this notebook is to independently reproduce and verify each numerical claim mentioned in the article regarding Surah An-Nahl using transparent and reproducible code.

##**Methodology**

Our website also provides an Abjad values Dataset, a Quran database in Uthmani Rasm-ul-Khat script, and a Surah names dataset. Please use these resources to cross-check and verify the data.

Extract and process the Arabic text programmatically using Python.

Count the occurrences of specific letters, words, and phrases mentioned in the article.

Reproduce the calculations and numerical patterns described.

Compare the computed results with the claims presented on the website for verification.

##**Notes**

All computations are performed using Python.

The analysis is designed to be transparent, reproducible, and verifiable.

The notebook can serve as a reference for further research on numerical and linguistic features in the Quran.

**Author:** Muhammad Usman (CEO & Co-Founder, Revolve AI)

**Environment:** Google Colab / Python bold text

***Verification Process Initiated***

Point 1:
A male bee has 16 chromosomes, while a female bee has 32, with the male being haploid (n) and the female diploid (2n), both multiples of 16.

Point2:
Surah An-Nahl has exactly 16 ruku, reflecting its surah number.


In [1]:
quran_url='https://docs.google.com/spreadsheets/d/1SlfFrgAuAn8X3_VZSFesAYCkODosAm2V/export?format=xlsx'
abjad_url='https://drive.google.com/uc?id=1lCILyB7HVVkPjHl5DrMleefIT-p9CkEI&export?format=csv'
surah_names_url='https://drive.google.com/uc?id=1q7-xno_wmYVatFeg7-kpYYxEkFyhuNt2&export?format=csv'

**Verification Using Code Started**

Point 3: In Surah An-Nahl, verse 16 is the shortest verse, which interestingly corresponds to the surah's number.

In [2]:

import pandas as pd

TARGET_SURAH = 16
df = pd.read_excel(quran_url)
surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


def count_words(text: str) -> int:
    """
    Count words by splitting on whitespace.
    """
    if not isinstance(text, str):
        return 0
    return len(text.split())

nahl = df[(df["Surah"] == TARGET_SURAH) & df["Verses"].notna()].copy()
nahl["word_count"] = nahl["Verses"].apply(count_words)
min_words = nahl["word_count"].min()
shortest_verses = nahl[nahl["word_count"] == min_words]

print(f"Shortest verse(s) in Surah an-Nahl (Surah {TARGET_SURAH}) by WORD count:")
for _, row in shortest_verses.iterrows():
    ayah_no = int(row["Ayah"])
    verse_text = row["Verses"]
    word_count = row["word_count"]
    print("-" * 60)
    print(f"Ayah number : {ayah_no}")
    print(f"Verse text  : {verse_text}")
    print(f"Word count  : {word_count}")


Shortest verse(s) in Surah an-Nahl (Surah 16) by WORD count:
------------------------------------------------------------
Ayah number : 16
Verse text  : وعلمت وبالنجم هم يهتدون
Word count  : 4


Point 4: In verse 16 of Surah An-Nahl, exactly 16 letters of the Arabic alphabet are absent, a remarkable linguistic pattern.

In [3]:


import pandas as pd

TARGET_SURAH = 16
TARGET_AYAH = 16

df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


ARABIC_ALPHABET = list("ابتثجحخدذرزسشصضطظعغفقكلمنهوي")

VARIANT_MAP = {
    "أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ئ": "ا", "ؤ": "ا", "ء": "ا",
    "ة": "ه",
    "ى": "ي",
}


def normalize_letter(ch: str):
    """
    Normalize a character to one of the 28 base Arabic letters:
    - Map common variants (أ، إ، آ، ٱ، ؤ، ئ، ء -> ا; ة -> ه; ى -> ي)
    - Ignore anything that is not a letter (spaces, punctuation, etc.)
    """
    if ch in VARIANT_MAP:
        return VARIANT_MAP[ch]
    if ch in ARABIC_ALPHABET:
        return ch
    return None


row = df[(df["Surah"] == TARGET_SURAH) & (df["Ayah"] == TARGET_AYAH)].iloc[0]
verse_text = row["Verses"]

present_letters = set()

for ch in verse_text:
    base = normalize_letter(ch)
    if base is not None:
        present_letters.add(base)

present_in_order = [l for l in ARABIC_ALPHABET if l in present_letters]
absent_letters = [l for l in ARABIC_ALPHABET if l not in present_letters]

print(f"Surah {TARGET_SURAH}, Ayah {TARGET_AYAH} text:")
print(verse_text)
print("")



print("\nAbsent letters (from 28 hijai letters):")
print(" ".join(absent_letters))
print(f"Number of absent letters: {len(absent_letters)}")


Surah 16, Ayah 16 text:
وعلمت وبالنجم هم يهتدون


Absent letters (from 28 hijai letters):
ث ح خ ذ ر ز س ش ص ض ط ظ غ ف ق ك
Number of absent letters: 16


Point 4: Verse 92 is the longest verse, containing 128 letters and 32 words, corresponding to the number of chromosomes in a female bee.

In [4]:

import pandas as pd
import re

TARGET_SURAH = 16
df = pd.read_excel(quran_url)
surah_nums = []
ayah_nums = []
current_surah = 1
current_ayah = 0
prev_blank = False
for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums

ARABIC_LETTER_RE = re.compile(r"[\u0621-\u064A]")
def count_letters(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return sum(1 for ch in text if ARABIC_LETTER_RE.match(ch))
def count_words(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return len(text.split())

nahl = df[(df["Surah"] == TARGET_SURAH) & df["Verses"].notna()].copy()
nahl["word_count"] = nahl["Verses"].apply(count_words)
nahl["letter_count"] = nahl["Verses"].apply(count_letters)
max_letters = nahl["letter_count"].max()
longest_verses = nahl[nahl["letter_count"] == max_letters]

print(f"Largest verse(s) in Surah an-Nahl (Surah {TARGET_SURAH}):")
for _, row in longest_verses.iterrows():
    ayah_no = int(row["Ayah"])
    verse_text = row["Verses"]
    word_count = int(row["word_count"])
    letter_count = int(row["letter_count"])

    print("-" * 70)
    print(f"Ayah number   : {ayah_no}")
    print(f"Verse text    : {verse_text}")
    print(f"Letter count  : {letter_count}")
    print(f"Word count    : {word_count}")


Largest verse(s) in Surah an-Nahl (Surah 16):
----------------------------------------------------------------------
Ayah number   : 92
Verse text    : ولا تكونوا كالتي نقضت غزلها من بعد قوة أنكثا تتخذون أيمنكم دخلا بينكم أن تكون أمة هي أربى من أمة إنما يبلوكم الله به وليبينن لكم يوم القيمة ما كنتم فيه تختلفون
Letter count  : 128
Word count    : 32


Surah An-Nahl contains 128 verses, a multiple of 16 that symbolizes its numerical harmony.

128 = 16 × 8

In [5]:
import pandas as pd


df = pd.read_excel(quran_url)


target_surah_no = 16
multiple_factor = 16


surah_data = []
current_verse_count = 0

for verse in df['Verses']:

    if pd.isna(verse) or str(verse).strip() == "":
        if current_verse_count > 0:
            surah_data.append(current_verse_count)
            current_verse_count = 0
        continue
    current_verse_count += 1


if current_verse_count > 0:
    surah_data.append(current_verse_count)


if len(surah_data) >= target_surah_no:
    total_verses = surah_data[target_surah_no - 1]

    if total_verses % multiple_factor == 0:
        factor = total_verses // multiple_factor
        print(f"Surah {target_surah_no} has {total_verses} verses = {multiple_factor} * {factor}")
    else:
        print(f"Surah {target_surah_no} has {total_verses} verses (not a multiple of {multiple_factor})")
else:
    print(f"Error: The file only contains data for {len(surah_data)} Surahs.")

Surah 16 has 128 verses = 16 * 8


**Divine Precision in Surah An-Nahl (16:68)**

Verse 68 contains 54 letters of which 16 are unique

# Arabic Letters and Their Variations  
*Variations are **not counted as separate letters**; they are treated as their base letter.*

- **ا (Alif)**  
  Variations: أ, إ, آ, ء, ؤ, ئ  
  _All these are counted as "ا"._

- **ي (Ya)**  
  Variations: ى  
  _Both ي and ى are counted as "ي"._

- **ه (Ha)**  
  Variations: ة  
  _Both ه and ة are counted as "ه"._

In [6]:
import pandas as pd


alif_variations = ['ا', 'أ', 'إ', 'آ', 'ء', 'ؤ', 'ئ']
ya_variations = ['ي', 'ى']
ha_variations = ['ه', 'ة']


dataset = pd.read_excel(quran_url)

target_surah, target_verse = 16, 68
current_surah, current_verse = 1, 1
verse_text = ""

for entry in dataset['Verses']:
    if pd.isna(entry) or str(entry).strip() == "":
        current_surah += 1
        current_verse = 1
        continue
    if current_surah == target_surah and current_verse == target_verse:
        verse_text = str(entry).strip()
        break
    current_verse += 1


letters_only = [char for char in verse_text if char != ' ']
unique_base_letters = set()

for char in letters_only:
    if char in alif_variations:
        unique_base_letters.add('BASE_ALIF')
    elif char in ya_variations:
        unique_base_letters.add('BASE_YA')
    elif char in ha_variations:
        unique_base_letters.add('BASE_HA')
    else:
        unique_base_letters.add(char)


print(f"Total Letters: {len(letters_only)}")
print(f"Unique Base Letters: {len(unique_base_letters)}")
print(f"Unique Letters List: {sorted(list(unique_base_letters))}")

Total Letters: 54
Unique Base Letters: 16
Unique Letters List: ['BASE_ALIF', 'BASE_YA', 'ب', 'ت', 'ج', 'ح', 'خ', 'ذ', 'ر', 'ش', 'ع', 'ك', 'ل', 'م', 'ن', 'و']


In verse no 68 From the beginning of the verse up to the word 'النحل' (including it), the phrase:

وأوحى ربك إلى النحل

Contains 16 letters

In [7]:
import pandas as pd


dataset = pd.read_excel(quran_url)

target_surah = 16
target_verse = 68
current_surah, current_verse = 1, 1
verse_content = ""

for entry in dataset['Verses']:
    if pd.isna(entry) or str(entry).strip() == "":
        current_surah += 1
        current_verse = 1
        continue
    if current_surah == target_surah and current_verse == target_verse:
        verse_content = str(entry).strip()
        break
    current_verse += 1

if verse_content:
    keyword = "النحل"
    end_pos = verse_content.find(keyword) + len(keyword)
    extracted_phrase = verse_content[:end_pos]

    cleaned_phrase = extracted_phrase.replace(" ", "")
    letter_count = len(cleaned_phrase)

    print(f"Phrase: {extracted_phrase}")
    print(f"Total Letter Count: {letter_count}")

Phrase: وأوحى ربك إلى النحل
Total Letter Count: 16


**Global Qur'anic Pattern**

All the 16th verses across the Qur'an (85 surahs) contain a total of 884 words, forming a global pattern.


**Surah An-Nahl **

In Surah An-Nahl, the word "Nahl" (النحل) appears at position 884, matching the global pattern.



**Global Qur'anic Pattern**

When the 16th verses from all 85 surahs are examined together, a remarkable pattern emerges.
They are found to contain exactly 3769 letters in total. This forms a stunning display of mathematical balance and divine design within the Qur'an.


**Surah An-Nahl Specific**

From the start of Surah An-Nahl to verse 68, there are exactly 3769 letters, aligning with the global pattern




In [8]:

import pandas as pd
import re
import unicodedata


TARGET_SURAH_NAHL = 16
TARGET_WORD_RAW = "النحل"


df = pd.read_excel(quran_url)


surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


def count_words(text: str) -> int:
    """Simple word count: split by whitespace."""
    if not isinstance(text, str):
        return 0
    return len(text.split())


ARABIC_LETTER_RE = re.compile(r"[\u0621-\u064A]")

def count_letters(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return sum(1 for ch in text if ARABIC_LETTER_RE.match(ch))


def strip_diacritics(s: str) -> str:
    """Remove Arabic diacritics (tashkeel) using Unicode combining marks."""
    decomposed = unicodedata.normalize("NFD", s)
    without_marks = "".join(
        ch for ch in decomposed if unicodedata.category(ch) != "Mn"
    )
    return unicodedata.normalize("NFC", without_marks)


def normalize_arabic_word(w: str) -> str:
    """
    Normalize an Arabic word for comparison:
    - Remove diacritics
    - Unify بعض أشكال الألف (ٱ، أ، إ، آ -> ا)
    - Remove non-Arabic characters (punctuation, digits, etc.)
    """
    w = strip_diacritics(w)
    w = (w.replace("ٱ", "ا")
           .replace("أ", "ا")
           .replace("إ", "ا")
           .replace("آ", "ا"))
    w = re.sub(r"[^\u0600-\u06FF]", "", w)
    return w


TARGET_WORD_NORM = normalize_arabic_word(TARGET_WORD_RAW)


ayah16_df = df[(df["Ayah"] == 16) & df["Verses"].notna()].copy()

ayah16_df["word_count"] = ayah16_df["Verses"].apply(count_words)
ayah16_df["letter_count"] = ayah16_df["Verses"].apply(count_letters)

num_surahs_with_16 = ayah16_df["Surah"].nunique()
total_words_in_ayah16 = int(ayah16_df["word_count"].sum())
total_letters_in_ayah16 = int(ayah16_df["letter_count"].sum())

print("=== A) Verse 16 across the Quran ===")
print(f"Number of surahs that have Ayah 16            : {num_surahs_with_16}")
print(f"Total number of words in ALL Ayah 16         : {total_words_in_ayah16}")
print(f"Total number of letters in ALL Ayah 16       : {total_letters_in_ayah16}")
print()



nahl_1_68 = df[
    (df["Surah"] == TARGET_SURAH_NAHL)
    & df["Ayah"].notna()
    & (df["Ayah"] >= 1)
    & (df["Ayah"] <= 68)
].copy()

nahl_1_68["word_count"] = nahl_1_68["Verses"].apply(count_words)
nahl_1_68["letter_count"] = nahl_1_68["Verses"].apply(count_letters)

total_words_nahl_1_68 = int(nahl_1_68["word_count"].sum())
total_letters_nahl_1_68 = int(nahl_1_68["letter_count"].sum())

print("=== B) Surah an-Nahl, verses 1–68 ===")

print(f"Total letters from start of Surah an-Nahl to Ayah 68 : {total_letters_nahl_1_68}")
print()



nahl_all = df[
    (df["Surah"] == TARGET_SURAH_NAHL) & df["Verses"].notna()
].copy()

total_words_until_target = 0
found = False
found_ayah = None

for _, row in nahl_all.iterrows():
    ayah_no = int(row["Ayah"])
    verse_text = str(row["Verses"])
    words = verse_text.split()

    for w in words:
        total_words_until_target += 1
        if normalize_arabic_word(w) == TARGET_WORD_NORM:
            found = True
            found_ayah = ayah_no
            break

    if found:
        break

print("=== C) Words in Surah an-Nahl until the word 'النحل' appears ===")
if found:
    print(f"'النحل' found in Surah {TARGET_SURAH_NAHL}, Ayah {found_ayah}.")
    print(f"Total number of words from the start of Surah an-Nahl up to and including the word 'النحل': {total_words_until_target}")
else:
    print("The word 'النحل' was NOT found in Surah an-Nahl using current normalization.")


=== A) Verse 16 across the Quran ===
Number of surahs that have Ayah 16            : 85
Total number of words in ALL Ayah 16         : 884
Total number of letters in ALL Ayah 16       : 3769

=== B) Surah an-Nahl, verses 1–68 ===
Total letters from start of Surah an-Nahl to Ayah 68 : 3769

=== C) Words in Surah an-Nahl until the word 'النحل' appears ===
'النحل' found in Surah 16, Ayah 68.
Total number of words from the start of Surah an-Nahl up to and including the word 'النحل': 884


**Surah An-Nahl Specific**

From the start of Surah An-Nahl to verse 68, there are exactly 3769 letters, aligning with the global pattern.
The bee-related verses (16:68–69) contain 37 words.
As the theme ends at verse 69, the number 3769 perfectly signifies the completion of this topic.

    **3769**

*   37 words in verses 68–69
*   69 verse where the bee theme ends





In [9]:

import pandas as pd

df = pd.read_excel(quran_url)

blank_indices = df[df["Verses"].isna()].index.to_list()

def get_surah_verses(df, blank_indices, surah_no: int) -> pd.Series:
    if surah_no == 1:
        start = 0
        end = blank_indices[0] - 1
    else:
        start = blank_indices[surah_no - 2] + 1
        end = blank_indices[surah_no - 1] - 1
    return df.loc[start:end, "Verses"].reset_index(drop=True)

def count_words(text: str) -> int:
    if pd.isna(text):
        return 0
    return len(str(text).split())


surah_no = 16
target_verses = [68, 69]
total=0
surah16 = get_surah_verses(df, blank_indices, surah_no)

for v in target_verses:
    verse_text = surah16.iloc[v - 1]
    word_count = count_words(verse_text)
    print(f"Surah {surah_no}, verse {v}:")
    print(verse_text)
    print("Number of words:", word_count)
    print("-" * 40)
    total=total+word_count
print("Total Words :",total)


Surah 16, verse 68:
وأوحى ربك إلى النحل أن اتخذي من الجبال بيوتا ومن الشجر ومما يعرشون
Number of words: 13
----------------------------------------
Surah 16, verse 69:
ثم كلي من كل الثمرت فاسلكي سبل ربك ذللا يخرج من بطونها شراب مختلف ألونه فيه شفاء للناس إن في ذلك لءاية لقوم يتفكرون
Number of words: 24
----------------------------------------
Total Words : 37


**Global Qur'anic Pattern**

Among the first 16 Surahs, 13 Surahs have verse 68.

Surah 13 contains 854 words and 43 verses.

Difference: 43 - 13 = 30

854 + 30 = 884

Prime factors: 22 x 13 x 17.

Middle factor is 13.

In [11]:
import pandas as pd

def get_prime_factors(n):
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors


dataset = pd.read_excel(quran_url)

surahs_metadata = []
current_surah_verses = []
surah_count = 0

for entry in dataset['Verses']:
    if pd.isna(entry) or str(entry).strip() == "":
        if current_surah_verses:
            surah_count += 1

            word_count = sum(len(str(v).split()) for v in current_surah_verses)
            surahs_metadata.append({
                'surah_no': surah_count,
                'verse_count': len(current_surah_verses),
                'word_count': word_count
            })
            current_surah_verses = []
        if surah_count == 16:
            break
        continue
    current_surah_verses.append(entry)

surahs_with_v68 = [s for s in surahs_metadata if s['verse_count'] >= 68]
count_v68 = len(surahs_with_v68)

surah_13 = surahs_metadata[12]
s13_verses = surah_13['verse_count']
s13_words = surah_13['word_count']


difference = s13_verses - 13
final_sum = s13_words + difference
factors = get_prime_factors(final_sum)


print(f"--- Global Quranic Pattern Verification ---")
print(f"1. Surahs (1-16) containing Verse 68: {count_v68}")
print(f"2. Surah 13 (Ar-Ra'd) Verse Count: {s13_verses}")
print(f"3. Surah 13 (Ar-Ra'd) Word Count: {s13_words}")
print(f"4. Surah 13 Difference (Verse Count - Surah No): {s13_verses} - 13 = {difference}")
print(f"5. Final Sum (Words + Difference): {s13_words} + {difference} = {final_sum}")
print(f"6. Prime Factors of {final_sum}: {factors}")

if len(factors) >= 3:
    middle_idx = len(factors) // 2
    print(f"   Middle Factor: {factors[middle_idx]}")

--- Global Quranic Pattern Verification ---
1. Surahs (1-16) containing Verse 68: 13
2. Surah 13 (Ar-Ra'd) Verse Count: 43
3. Surah 13 (Ar-Ra'd) Word Count: 854
4. Surah 13 Difference (Verse Count - Surah No): 43 - 13 = 30
5. Final Sum (Words + Difference): 854 + 30 = 884
6. Prime Factors of 884: [2, 2, 13, 17]
   Middle Factor: 13


Surah An-Nahl Specific

The word "An-Nahl" appears only once in the Quran, in Verse 68.
Verse 68 contains 13 words.
13 x 68 = 884

Total Surahs with verse 68 until Surah An-Nahl: 13

Among the first 16 Surahs, 3 Surahs do not have verse 68.
These Surahs are: 1, 13, 14.

1 + 13 + 14 = 28

Exactly equal to 28 Hijai Alphabets in Arabic

In [13]:
import pandas as pd

df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums

def count_words(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return len(text.split())

df["word_count"] = df["Verses"].apply(count_words)

TARGET_SURAH = 16
TARGET_WORD = "النحل"

word_occurrences = df[df["Verses"].str.contains(TARGET_WORD, na=False)]

print("Occurrences of 'An-Nahl' in the Quran:")
for _, row in word_occurrences.iterrows():
    print(f"Surah {int(row['Surah'])}, Ayah {int(row['Ayah'])}, Words in verse: {row['word_count']}")
verse_68_count = df[(df["Ayah"] == 68) & (df["Surah"] <= TARGET_SURAH)].shape[0]
print(f"\nTotal Surahs with verse 68 until Surah An-Nahl: {verse_68_count}")
if not word_occurrences.empty:
    words_in_verse = word_occurrences.iloc[0]["word_count"]
    result = words_in_verse * 68
    print(f"{words_in_verse} x 68 = {result}")

Occurrences of 'An-Nahl' in the Quran:
Surah 16, Ayah 68, Words in verse: 13

Total Surahs with verse 68 until Surah An-Nahl: 13
13 x 68 = 884


**Global Qur'anic Pattern**
Surah An-Nahl includes 8 verses that are multiples of 16, (16, 32, 48, 64, 80, 96, 112, 128).

Together, these verses contain 119 words, the Abjad value of "An-Nahl"

In [14]:

import pandas as pd


df_abjad = pd.read_csv(abjad_url)

abjad_map = dict(zip(df_abjad["Letter"], df_abjad["Abjad Value"]))

word = "النحل"

total_value = 0
details = []

for ch in word:
    value = abjad_map.get(ch, 0)
    details.append((ch, value))
    total_value += value
print(f"Abjad breakdown for '{word}':")
for ch, v in details:
    print(f"{ch} -> {v}")

print(f"\nTotal Abjad value of '{word}' = {total_value}")


Abjad breakdown for 'النحل':
ا -> 1
ل -> 30
ن -> 50
ح -> 8
ل -> 30

Total Abjad value of 'النحل' = 119


In [15]:

import pandas as pd

TARGET_SURAH = 16
MULTIPLE_AYAT = [16, 32, 48, 64, 80, 96, 112, 128]


df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


def count_words(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return len(text.split())


s16_mult = df[
    (df["Surah"] == TARGET_SURAH) &
    (df["Ayah"].isin(MULTIPLE_AYAT)) &
    df["Verses"].notna()
].copy()

s16_mult["word_count"] = s16_mult["Verses"].apply(count_words)

print("Words in Surah an-Nahl verses that are multiples of 16:")
for _, row in s16_mult.sort_values("Ayah").iterrows():
    ayah = int(row["Ayah"])
    verse = row["Verses"]
    wc = int(row["word_count"])
    print("-" * 60)
    print(f"Ayah {ayah}:")
    print(verse)
    print(f"Word count: {wc}")

total_words = int(s16_mult["word_count"].sum())
print("\nTotal number of words in Ayat 16, 32, 48, 64, 80, 96, 112, 128 of Surah an-Nahl:")
print(total_words)


Words in Surah an-Nahl verses that are multiples of 16:
------------------------------------------------------------
Ayah 16:
وعلمت وبالنجم هم يهتدون
Word count: 4
------------------------------------------------------------
Ayah 32:
الذين تتوفيهم الملئكة طيبين يقولون سلم عليكم ادخلوا الجنة بما كنتم تعملون
Word count: 12
------------------------------------------------------------
Ayah 48:
اولم يروا إلى ما خلق الله من شيء يتفيؤا ظلله عن اليمين والشمائل سجدا لله وهم دخرون
Word count: 17
------------------------------------------------------------
Ayah 64:
وما أنزلنا عليك الكتب إلا لتبين لهم الذي اختلفوا فيه وهدى ورحمة لقوم يؤمنون
Word count: 14
------------------------------------------------------------
Ayah 80:
والله جعل لكم من بيوتكم سكنا وجعل لكم من جلود الأنعم بيوتا تستخفونها يوم ظعنكم ويوم إقامتكم ومن أصوافها وأوبارها وأشعارها أثثا ومتعا إلى حين
Word count: 25
------------------------------------------------------------
Ayah 96:
ما عندكم ينفد وما عند الله باق ولنجزين الذين صبروا أ

Surah An-Nahl Specific

From the start of the Qur'an up to verse 128 of Surah An-Nahl, there are exactly 119 verses numbered as multiples of 16

In [16]:


surah_verse_counts = {
    1: 7,    # Al-Fatiha
    2: 286,  # Al-Baqarah
    3: 200,  # Aal Imran
    4: 176,  # An-Nisa
    5: 120,  # Al-Ma'idah
    6: 165,  # Al-An'am
    7: 206,  # Al-A'raf
    8: 75,   # Al-Anfal
    9: 129,  # At-Tawbah
    10: 109, # Yunus
    11: 123, # Hud
    12: 111, # Yusuf
    13: 43,  # Ar-Ra'd
    14: 52,  # Ibrahim
    15: 99,  # Al-Hijr
    16: 128, # An-Nahl
}

def count_multiples_of_16(limit_surah=16, limit_ayah=128):
    total_multiples = 0

    for surah in range(1, limit_surah + 1):
        total_ayahs = surah_verse_counts[surah]

        if surah < limit_surah:
            max_ayah = total_ayahs
        else:
            max_ayah = limit_ayah

        for ayah in range(16, max_ayah + 1, 16):
            total_multiples += 1

    return total_multiples

total_count = count_multiples_of_16()
print("Total count of verses with ayah numbers multiple of 16 up to 16:128 =", total_count)


Total count of verses with ayah numbers multiple of 16 up to 16:128 = 119




### 🟢 **5 Natural Creations in Verse 11**
**11 is the 5th prime number**

| Word | Digit Sum | Letters | Total |
| :--- | :---: | :---: | :---: |
| **الزرع** 🌾 | 11 | 5 | **16** |
| **الزيتون** 🫒 | 9 | 7 | **16** |
| **النخيل** 🌴 | 10 | 6 | **16** |
| **الأعنب** 🍇 | 10 | 6 | **16** |
| **الثمرت** 🍊 | 10 | 6 | **16** |

---

**### Abjad Value & Digit Sum of First Word (الزرع)**

* **ا (Alif)** = 1
* **ل (Laam)** = 30
* **ز (Zaay)** = 7
* **ر (Raa)** = 200
* **ع (Ayn)** = 70

> **Total = 308 ➔ 3 + 0 + 8 = 11**




**The Totals**
Total Sum: 30 + 50 = 80

*   Letters Sum: 30
*   Abjad Digit Sum: 50







**The Link to Surah 16**



The total sum of 80 directly relates to the Surah number:



*   80 = 16 * 5
*   16 = The number of the Surah (An-Nahl).
*   5 = The number of resource types you identified in the verse.






**The Average Reinforcement**

The averages also lead back to the number 16:



*   Average of 30: 6
*   Average of 50: 10






Sum of Averages: 6 + 10 = 16 (The Surah number).

Total =80 and digit sum 80 is again 8 and if we multiply 8*16=128 it's again = no of verses in this surah.





In [17]:

import pandas as pd



df_abjad = pd.read_csv(abjad_url)


abjad_map = dict(zip(df_abjad["Letter"], df_abjad["Abjad Value"]))


words = ["الزرع", "الزيتون", "النخيل", "الأعنب", "الثمرت"]

def count_letters(word: str) -> int:
    """Count only characters that exist in the Abjad map and have non-zero value."""
    return sum(1 for ch in word if ch in abjad_map and abjad_map[ch] != 0)

def abjad_value(word: str) -> int:
    """Sum Abjad values of all letters in the word."""
    return sum(abjad_map.get(ch, 0) for ch in word)

def digit_sum(n: int) -> int:
    """Single digit-sum: e.g. 308 -> 3 + 0 + 8 = 11."""
    n = abs(int(n))
    return sum(int(d) for d in str(n))

total_letters = 0
total_digit_sum_abjad = 0
total_per_word_combined = 0

print("Word breakdown:\n")

for w in words:
    letters = count_letters(w)
    val = abjad_value(w)
    ds = digit_sum(val)
    per_word_total = letters + ds

    total_letters += letters
    total_digit_sum_abjad += ds

    print(f"Word: {w}")
    print(f"  Letters                 : {letters}")
    print(f"  Abjad value             : {val}")
    print(f"  Digit-sum(Abjad)        : {ds}")
    print(f"  Total (letters + digit-sum): {per_word_total}")
    print("-" * 40)


final_total = total_letters + total_digit_sum_abjad

print("\n=== Totals across all 5 words ===")
print(f"Total letters                           : {total_letters}")
print(f"Total digit-sum of Abjad values         : {total_digit_sum_abjad}")
print(f"Final total (letters + digit-sums)      : {final_total}")


Word breakdown:

Word: الزرع
  Letters                 : 5
  Abjad value             : 308
  Digit-sum(Abjad)        : 11
  Total (letters + digit-sum): 16
----------------------------------------
Word: الزيتون
  Letters                 : 7
  Abjad value             : 504
  Digit-sum(Abjad)        : 9
  Total (letters + digit-sum): 16
----------------------------------------
Word: النخيل
  Letters                 : 6
  Abjad value             : 721
  Digit-sum(Abjad)        : 10
  Total (letters + digit-sum): 16
----------------------------------------
Word: الأعنب
  Letters                 : 6
  Abjad value             : 154
  Digit-sum(Abjad)        : 10
  Total (letters + digit-sum): 16
----------------------------------------
Word: الثمرت
  Letters                 : 6
  Abjad value             : 1171
  Digit-sum(Abjad)        : 10
  Total (letters + digit-sum): 16
----------------------------------------

=== Totals across all 5 words ===
Total letters                           : 3

### **Arabic word from "honey" (عسل) 🍯 & its Arabic letter positions**

* **ع (Ayn)** = 18th letter
* **س (Seen)** = 12th letter
* **ل (Laam)** = 23rd letter

> **Sum = 53 ➔ 16th prime number**

In [18]:


arabic_alphabet = list("ابتثجحخدذرزسشصضطظعغفقكلمنهوي")

def letter_order(letter: str) -> int:
    """
    Return 1-based order of the letter in the hijai alphabet.
    Raises ValueError if letter not in the list.
    """
    return arabic_alphabet.index(letter) + 1

def is_prime(n: int) -> bool:
    """Check if n is a prime number."""
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0:
        return False
    i = 3
    while i * i <= n:
        if n % i == 0:
            return False
        i += 2
    return True

def prime_index(p: int):
    """
    If p is prime, return its index in the sequence of primes:
    2 -> 1, 3 -> 2, 5 -> 3, ...
    If p is not prime, return None.
    """
    if not is_prime(p):
        return None

    count = 0
    num = 2
    while num <= p:
        if is_prime(num):
            count += 1
            if num == p:
                return count
        num += 1
    return None

word = "عسل"


orders = [letter_order(ch) for ch in word]


sum_orders = sum(orders)

is_sum_prime = is_prime(sum_orders)
prime_pos = prime_index(sum_orders) if is_sum_prime else None

print(f"Word          : {word}")
print(f"Letter orders : {orders}")
print(f"Sum of orders : {sum_orders}")
print(f"Is sum prime? : {is_sum_prime}")
if is_sum_prime:
    print(f"Prime index   : {prime_pos}  (position of {sum_orders} among the primes)")


Word          : عسل
Letter orders : [18, 12, 23]
Sum of orders : 53
Is sum prime? : True
Prime index   : 16  (position of 53 among the primes)


# Verses with exactly 16 words
### *The Numerical Signature of Surah An-Nahl (The Bee)*

---

| **Feature** | **Verse Reference** | **Prime Index / Calculation** |
| :--- | :---: | :--- |
| **First appearance** | **16:11** | **5th prime** number |
| **Last appearance** | **16:103** | **27th prime** number |

---

### **Biological & Structural Symmetry**

> **Chromosomes in a female bee:** > # <center> $5 + 27 = \mathbf{32}$ </center>
> *(The sum of the prime positions matches the chromosome count)*

---

> **Total Surahs in the Quran:** > # <center> $103 + 11 = \mathbf{114}$ </center>
> *(The sum of the verse numbers equals the total chapters in the Quran)*



In [19]:

import pandas as pd

def is_prime(n: int) -> bool:
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

def prime_index(p: int) -> int:
    """Return 1-based index of prime p in sequence of primes: 2->1, 3->2, 5->3..."""
    if not is_prime(p):
        return None
    count = 0
    num = 2
    while num <= p:
        if is_prime(num):
            count += 1
            if num == p:
                return count
        num += 1
    return None

df = pd.read_excel(quran_url)

surahs = []
ayahs = []
cur_surah = 0
cur_ayah = 0
last_was_sep = True

for _, row in df.iterrows():
    text = row["Verses"]
    num = row["Numbers"]
    is_sep = pd.isna(text) or (pd.notna(num) and num == 0)
    if is_sep:
        surahs.append(None)
        ayahs.append(None)
        last_was_sep = True
        continue

    if last_was_sep:
        cur_surah += 1
        cur_ayah = 1
    else:
        cur_ayah += 1

    surahs.append(cur_surah)
    ayahs.append(cur_ayah)
    last_was_sep = False

df["Surah"] = surahs
df["Ayah"] = ayahs


nahl = df[df["Surah"] == 16].copy()

nahl["WordCount"] = (
    nahl["Verses"]
    .astype(str)
    .str.strip()
    .str.split()
    .str.len()
)


ayah_with_16_words = (
    nahl[nahl["WordCount"] == 16]["Ayah"]
    .dropna()
    .astype(int)
    .tolist()
)

print("Verses with exactly 16 words in Surah An-Nahl:")
print(ayah_with_16_words)


if ayah_with_16_words:
    first_ayah = ayah_with_16_words[0]
    last_ayah = ayah_with_16_words[-1]

    first_prime_order = prime_index(first_ayah) if is_prime(first_ayah) else None
    last_prime_order = prime_index(last_ayah) if is_prime(last_ayah) else None

    print("\nPrime check:")
    print(f"First Ayah: {first_ayah}, Prime Order: {first_prime_order}")
    print(f"Last Ayah: {last_ayah}, Prime Order: {last_prime_order}")

    if first_prime_order and last_prime_order:
        total_prime_order_sum = first_prime_order + last_prime_order
        print(f"Sum of prime orders: {total_prime_order_sum} same as chromosomes in female bee")
        print(f"Sum of verses orders: {last_ayah+first_ayah} same as total number of chapter's in quran")
    else:
        print("Either first or last Ayah is not prime. Cannot compute sum of prime orders.")


Verses with exactly 16 words in Surah An-Nahl:
[11, 45, 65, 90, 103]

Prime check:
First Ayah: 11, Prime Order: 5
Last Ayah: 103, Prime Order: 27
Sum of prime orders: 32 same as chromosomes in female bee
Sum of verses orders: 114 same as total number of chapter's in quran


## Key Numerical Harmony
**Four Elements of Divine Mathematical Unity**

* **Verse Numbers: 1360** (16 × 85)
  * *16th verses across 85 surahs in Quran*
* **Total Words: 884**
  * *Words in all 16th verses in Quran*
* **Surah Number: 16**
  * *Position of Surah An-Nahl in Quran*
* **Words in Surah: 1844**
  * *Total words in Surah An-Nahl*

---

### DIVINE UNITY

**1360 + 884 + 16 + 1844 = 4104**

> ✨ **Perfect Alignment:** This sum of **4104** precisely matches the Abjad value of verse 68, demonstrating the intricate numerical harmony and divine mathematical structure woven throughout Surah An-Nahl.




***Most of the points have already been verified above***

In [27]:
import pandas as pd

df = pd.read_excel(quran_url)

surahs = []
ayahs = []
cur_surah = 0
cur_ayah = 0
last_was_sep = True

for _, row in df.iterrows():
    text = row["Verses"]
    num = row["Numbers"]

    is_sep = pd.isna(text) or (pd.notna(num) and num == 0)

    if is_sep:
        surahs.append(None)
        ayahs.append(None)
        last_was_sep = True
        continue

    if last_was_sep:
        cur_surah += 1
        cur_ayah = 1
    else:
        cur_ayah += 1

    surahs.append(cur_surah)
    ayahs.append(cur_ayah)
    last_was_sep = False

df["Surah"] = surahs
df["Ayah"] = ayahs

df_clean = df.dropna(subset=["Surah", "Ayah"]).copy()

df_clean["WordCount"] = (
    df_clean["Verses"]
    .astype(str)
    .str.strip()
    .str.split()
    .str.len()
)

nahl = df_clean[df_clean["Surah"] == 16]
total_words_nahl = int(nahl["WordCount"].sum())

verse_16_all = df_clean[df_clean["Ayah"] == 16]
words_16th_verses = int(verse_16_all["WordCount"].sum())

surah_position = 16
calc_1360 = 16 * 85

final_total = calc_1360 + words_16th_verses + surah_position + total_words_nahl

df_abjad = pd.read_csv(abjad_url)
abjad_dict = dict(zip(df_abjad['Letter'], df_abjad['Abjad Value']))

def calculate_abjad(text):
    return sum(abjad_dict.get(ch, 0) for ch in str(text))

verse_68_text = df_clean[
    (df_clean["Surah"] == 16) & (df_clean["Ayah"] == 68)
]["Verses"].iloc[0]

abjad_68 = calculate_abjad(verse_68_text)

print("=" * 75)
print(" 🌟 SURAH AN-NAHL NUMERICAL ANALYSIS 🌟")
print("=" * 75)

print(f"🔹 16 × 85                         = {calc_1360}")
print(f"🔹 Words in all 16th verses        = {words_16th_verses}")
print(f"🔹 Surah Position (An-Nahl)        = {surah_position}")
print(f"🔹 Total words in Surah An-Nahl    = {total_words_nahl}")

print("-" * 75)
print(f"✅ FINAL TOTAL: {calc_1360} + {words_16th_verses} + {surah_position} + {total_words_nahl} = {final_total}")

print("=" * 75)
print(" 📖 ABJAD VALUE ANALYSIS 📖")
print("=" * 75)

print(f"🔹 Surah 16, Verse 68:")
print(verse_68_text)
print(f"\n🔹 Abjad Value: {abjad_68}")

print("=" * 75)

 🌟 SURAH AN-NAHL NUMERICAL ANALYSIS 🌟
🔹 16 × 85                         = 1360
🔹 Words in all 16th verses        = 884
🔹 Surah Position (An-Nahl)        = 16
🔹 Total words in Surah An-Nahl    = 1844
---------------------------------------------------------------------------
✅ FINAL TOTAL: 1360 + 884 + 16 + 1844 = 4104
 📖 ABJAD VALUE ANALYSIS 📖
🔹 Surah 16, Verse 68:
وأوحى ربك إلى النحل أن اتخذي من الجبال بيوتا ومن الشجر ومما يعرشون

🔹 Abjad Value: 4104


## Mathematical Harmony in Surah An-Nahl

### Divine Numerical Patterns in the Final Verse

The final verse **(128)** of **Surah An-Nahl** contains exactly **8 words** and **32 letters**.  
When multiplied together, they produce a perfect power of **16**.


The final verse of Surah An-Nahl displays a mathematical structure involving the number **16**:

- 8 words  
- 32 letters  
- 8 × 32 = 256 = **16²**
- 128 × 32 = 4096 = **16³**

These relationships create a consistent numerical pattern connected to the **Surah number (16)** and its **total number of verses (128)**.

In [22]:

import pandas as pd
import re

TARGET_SURAH = 16
df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:

        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums



def count_words(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return len(text.split())


ARABIC_LETTER_RE = re.compile(r"[\u0621-\u064A]")

def count_letters(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return sum(1 for ch in text if ARABIC_LETTER_RE.match(ch))

surah_16 = df[df["Surah"] == TARGET_SURAH]

last_ayah_num = int(surah_16["Ayah"].max())
last_verse_row = surah_16[surah_16["Ayah"] == last_ayah_num].iloc[0]

verse_text = last_verse_row["Verses"]
word_count = count_words(verse_text)
letter_count = count_letters(verse_text)

print(f"Surah {TARGET_SURAH}, last ayah = {last_ayah_num}")
print("Verse text:")
print(verse_text)
print()
print(f"Number of words  : {word_count}")
print(f"Number of letters: {letter_count}")


Surah 16, last ayah = 128
Verse text:
ان الله مع الذين اتقوا والذين هم محسنون

Number of words  : 8
Number of letters: 32


**There are six verses in Surah An-Nahl whose Abjad numerical values are divisible by 16.**




### 🧮 Combined Totals in these 6 verses

| Total Words | Sum of Abjad | ÷ 16 |
| :---: | :---: | :---: |
| **87** | **28,432** | **1,777** |


***This point is connected with the next two markdown sections***

In [23]:

import pandas as pd
TARGET_SURAH = 16

df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():
        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


def count_words(text: str) -> int:
    """Simple word count by whitespace split."""
    if not isinstance(text, str):
        return 0
    return len(text.split())


df["Numbers"] = pd.to_numeric(df["Numbers"], errors="coerce")


nahl = df[
    (df["Surah"] == TARGET_SURAH) &
    df["Verses"].notna() &
    df["Numbers"].notna()
].copy()

nahl["is_divisible_16"] = (nahl["Numbers"] % 16 == 0)

nahl_div16 = nahl[nahl["is_divisible_16"]].copy()

num_verses_div16 = len(nahl_div16)

nahl_div16["word_count"] = nahl_div16["Verses"].apply(count_words)
total_words_div16 = int(nahl_div16["word_count"].sum())


print("Surah an-Nahl (Surah 16) — verses with Abjad value divisible by 16")
print(f"Number of verses with Numbers % 16 == 0: {num_verses_div16}")
print(f"Total number of words in these verses  : {total_words_div16}")

for _, row in nahl_div16.sort_values("Ayah").iterrows():
    ayah = int(row["Ayah"])
    abjad_val = int(row["Numbers"])
    wc = int(row["word_count"])
    print("-" * 60)
    print(f"Ayah {ayah} | Abjad (Numbers) = {abjad_val} | Words = {wc}")
    print(row["Verses"])


Surah an-Nahl (Surah 16) — verses with Abjad value divisible by 16
Number of verses with Numbers % 16 == 0: 6
Total number of words in these verses  : 87
------------------------------------------------------------
Ayah 2 | Abjad (Numbers) = 3344 | Words = 18
ينزل الملئكة بالروح من أمره على من يشاء من عباده أن أنذروا أنه لا إله إلا أنا فاتقون
------------------------------------------------------------
Ayah 17 | Abjad (Numbers) = 3280 | Words = 7
افمن يخلق كمن لا يخلق أفلا تذكرون
------------------------------------------------------------
Ayah 19 | Abjad (Numbers) = 1632 | Words = 6
والله يعلم ما تسرون وما تعلنون
------------------------------------------------------------
Ayah 22 | Abjad (Numbers) = 3376 | Words = 11
الهكم إله وحد فالذين لا يؤمنون بالاءخرة قلوبهم منكرة وهم مستكبرون
------------------------------------------------------------
Ayah 61 | Abjad (Numbers) = 7712 | Words = 23
ولو يؤاخذ الله الناس بظلمهم ما ترك عليها من دابة ولكن يؤخرهم إلى أجل مسمى فإذا جاء أجلهم لا يستءخر

**## Verses in Perfect Balance**
**Seven Verses with 16 Words or Multiples of 16**

> There are **7 verses** in Surah An-Nahl that contain either **16 words** or a **multiple of 16 words**, revealing yet another layer of divine mathematical precision.

### ✅ The Seven Verses
**Verse 11** | **Verse 35** | **Verse 45** | **Verse 65** | **Verse 90** | **Verse 92** | **Verse 103**

* **Sum of verse numbers:** 11 + 35 + 45 + 65 + 90 + 92 + 103 = **441**

---

### First Calculation: Adding the Number of Verses

* **441** (sum of verses) + **7** (number of verses) = **448**

⬇️

### 448 ÷ 16 = 28
* *Exactly equal to 28 Hijai alphabets*
* *Perfect divisibility by 16*

In [24]:

import pandas as pd

TARGET_SURAH = 16

df = pd.read_excel(quran_url)
surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():

        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:
        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums


def count_words(text: str) -> int:
    """Count words by splitting on whitespace."""
    if not isinstance(text, str):
        return 0
    return len(text.split())



nahl = df[(df["Surah"] == TARGET_SURAH) & df["Verses"].notna()].copy()
nahl["word_count"] = nahl["Verses"].apply(count_words)


nahl_mult_16 = nahl[nahl["word_count"] % 16 == 0]

verse_numbers = sorted(int(a) for a in nahl_mult_16["Ayah"])
sum_of_verses = sum(verse_numbers)

print(f"Surah An-Nahl (Surah {TARGET_SURAH})")
print(f"Number of verses with 16 or multiple of 16 words: {len(verse_numbers)}")
print("Verse numbers:", verse_numbers)
print(f"Sum of these verse numbers: {sum_of_verses}")



Surah An-Nahl (Surah 16)
Number of verses with 16 or multiple of 16 words: 7
Verse numbers: [11, 35, 45, 65, 90, 92, 103]
Sum of these verse numbers: 441


**### Second Calculation: Adding the Abjad Word Count**

* **441** (sum of verses) + **87** (Abjad word count) = **528**
  * *87 is the total words in the 6 verses whose Abjad values are divisible by 16*

⬇️

### 528 ÷ 16 = 33
* *Perfect divisibility by 16*

---

### Another Layer of Balance

* **33 - 28 = 5**
  * *The difference between the two division results*

⬇️

> In Surah An-Nahl, there are exactly **5 verses** with precisely **16 words** each, perfectly matching this mathematical difference!

In [25]:


import pandas as pd
TARGET_SURAH = 16

df = pd.read_excel(quran_url)

surah_nums = []
ayah_nums = []

current_surah = 1
current_ayah = 0
prev_blank = False

for verse in df["Verses"]:
    if isinstance(verse, str) and verse.strip():

        current_ayah += 1
        surah_nums.append(current_surah)
        ayah_nums.append(current_ayah)
        prev_blank = False
    else:

        surah_nums.append(None)
        ayah_nums.append(None)
        if not prev_blank:
            current_surah += 1
            current_ayah = 0
        prev_blank = True

df["Surah"] = surah_nums
df["Ayah"] = ayah_nums



def count_words(text: str) -> int:
    """Count words by splitting on whitespace."""
    if not isinstance(text, str):
        return 0
    return len(text.split())


nahl = df[(df["Surah"] == TARGET_SURAH) & df["Verses"].notna()].copy()
nahl["word_count"] = nahl["Verses"].apply(count_words)

nahl_16_words = nahl[nahl["word_count"] == 16]
verse_numbers_16 = sorted(int(a) for a in nahl_16_words["Ayah"])
count_16 = len(verse_numbers_16)

print(f"Surah An-Nahl (Surah {TARGET_SURAH})")
print(f"Number of verses with EXACTLY 16 words: {count_16}")
print("Verse numbers with 16 words:", verse_numbers_16)

Surah An-Nahl (Surah 16)
Number of verses with EXACTLY 16 words: 5
Verse numbers with 16 words: [11, 45, 65, 90, 103]
